services:
  - type: web
    name: estrattore-playlist
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install-deps
      python -m playwright install chromium --with-deps
      python -c "from playwright.sync_api import sync_playwright; p=sync_playwright().start(); p.chromium.launch(); p.stop()"
    startCommand: python estrattore.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    plan: free
